import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { geistMono } from "@/lib/fonts";
import { Providers } from "../components/providers/providers";

/**
 * Load Inter font from Google with Latin subset
 */
const inter = Inter({ subsets: ["latin"] });

/**
 * RootLayout Metadata
 * ------------------
 * Sets default title and description for the app.
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/**
 * RootLayout Component
 * -------------------
 * - Wraps the entire application.
 * - Applies global fonts (Inter + Geist Mono variable font).
 * - Wraps children in Providers (e.g., context providers, state management).
 *
 * Props:
 * - children: All nested page components to render inside the layout.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${geistMono.variable}`}>
      <body className={inter.className}>
        {/* Wrap app with Providers */}
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
